# Generated by Django 5.2.4 on 2025-07-08 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gameranking',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='gameranking',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameranking',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='gameranking',
            name='score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(default='unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='long_description',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='minimum_system_requirement',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_english_reviews',
            field=models.IntegerField(default='unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_reviews_from_purchased_people',
            field=models.IntegerField(default='unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='overall_player_rating',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='recommend_system_requirement',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='gameranking',
            name='game_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='gameranking',
            name='genre',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='gameranking',
            name='rank',
            field=models.IntegerField(default='unknown'),
        ),
        migrations.AddField(
            model_name='gameranking',
            name='rank_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='funny',
            field=models.IntegerField(default='unknown'),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.IntegerField(default='unknown'),
        ),
        migrations.AddField(
            model_name='review',
            name='hours_played',
            field=models.FloatField(default='unknown'),
        ),
        migrations.AddField(
            model_name='review',
            name='recommendation',
            field=models.BooleanField(default='unknown'),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
