# Generated by Django 5.2.4 on 2025-07-08 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_description_remove_game_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_english_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_reviews_from_purchased_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameranking',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='funny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='hours_played',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
