# Generated by Django 5.2.4 on 2025-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_number_of_english_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_english_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
